### ISSUE TITLE
3px space at the bottom

### ISSUE THREAD

**Issue by tibotiber** [williamngan/react-pts-canvas#2] opened 2019-06-04 08:08 UTC
I've been having an issue where there are a 3-annoying-little-pixels space at the bottom between the container and the canvas. Just wanted to highlight that I got rid of it by adding `lineHeight: 0` to the `style` prop. Not really an issue with the lib per se, but might be useful for others. Feel free to close ;)

**Comment by williamngan** [comment] 2019-06-04 08:45
Hi @tibotiber - thanks for reporting. I can't seem to reproduce the bug in the examples [here](https://williamngan.github.io/pts-react-example/build/). 

If possible, can you share the code snippet? Would definitely like to fix it. Thank you!

**Comment by tibotiber** [comment] 2019-06-19 07:57
Hi @williamngan, I just got back to this, thanks for your patience. So I've checked after you told me you didn't have the problem on your end and the issue was mine. I'm using the [Ant Design](https://ant.design/) component library and it leaks CSS, so I ended up having a `line-height` applied to `*`, sorry 🤦‍♂️.

Do you think it would be worth defaulting that `lineHeight: 0` to avoid contextual issue? Because it makes no sense to have such a space in the first place.

**Comment by williamngan** [comment] 2019-06-21 09:16
No problem. I wonder if that's because the default canvas 'display' is 'inline'. If we changes it to 'display: block', would that solve the problem? That might be better than 'line-height: 0'.

I cannot quite reproduce the line-height problem. Can you check if 'display: block' would fix it?

**Comment by tibotiber** [comment] 2019-06-21 12:54
`display: block` did not change anything. I've tried to create a minimal reproduction repo but couldn't manage although I believe I copied all the CSS of both the canvas and the container. This is probably some weird CSS issue due to Ant Design, they add a lot of CSS which I'm not all familiar with.

I wish I could share the codebase this happens in but I can't unfortunately.

My guess is this can be ignored since we're trying so hard to reproduce but can't manage. Worst case someone should find this issue and add some information. What do you think?

**Comment by williamngan** [comment] 2019-06-22 08:25
Sounds good. Thanks for checking. If this comes up again, let's investigate more. Closing it for now.

**Closed by williamngan** 2019-06-22 08:25 UTC
